/* automatically generated by rust-bindgen */

pub const REG_A: u32 = 12345;
pub const REG_B: u32 = 12346;
pub const REG_C: u32 = 12347;
pub const REG_D: u32 = 12348;
pub const REG_E: u32 = 12349;
pub const REG_F: u32 = 12350;
